build.gradle, src/main/resources/application-prod.yml, src/main/resources/application.yml
Closes #9 
- `build.gradle`에 mapstruct 라이브러리 추가
- `build.gradle`에 testcontainer 라이브러리 추가
- `application.yml`, `application-prod.yml`에 `logging.level.org.hibernate.SQL` 옵션 삭제
- #9
=> feat: mapstruct 라이브러리 추가 및 application.yml 불필요한 설정 삭제

src/main/java/com/harusari/chainware/disposal/command/application/controller/DisposalCommandController.java, src/main/java/com/harusari/chainware/disposal/command/application/dto/DisposalCommandRequestDto.java, src/main/java/com/harusari/chainware/disposal/command/application/service/DisposalCommandService.java, src/main/java/com/harusari/chainware/disposal/command/application/service/DisposalCommandServiceImpl.java, src/main/java/com/harusari/chainware/disposal/command/domain/aggregate/Disposal.java, src/main/java/com/harusari/chainware/disposal/command/domain/repository/DisposalRepository.java, src/main/java/com/harusari/chainware/disposal/command/infrastructure/repository/JpaDisposalRepository.java, src/main/java/com/harusari/chainware/disposal/query/controller/DisposalQueryController.java, src/main/java/com/harusari/chainware/disposal/query/dto/DisposalListDto.java, src/main/java/com/harusari/chainware/disposal/query/dto/DisposalListResponseDto.java, src/main/java/com/harusari/chainware/disposal/query/dto/DisposalSearchRequestDto.java, src/main/java/com/harusari/chainware/disposal/query/mapper/DisposalQueryMapper.java, src/main/java/com/harusari/chainware/disposal/query/service/DisposalQueryService.java, src/main/java/com/harusari/chainware/disposal/query/service/DisposalQueryServiceImpl.java, src/main/java/com/harusari/chainware/franchise/command/domain/repository/FranchiseRepository.java, src/main/java/com/harusari/chainware/warehouse/command/domain/repository/WarehouseRepository.java, src/main/resources/mappers/disposal/DisposalQueryMapper.xml
Closes #22 
- 가맹점/창고/반품 폐기 등록 및 가맹점 관리자/창고 관리자/ 일반,책임 관리자 폐기 조회
- 추후 프론트엔드에서 권한 별 검색조건 hidden 처리
- DisposalCommandServiceImpl에 폐기 처리 시 재고 감소 처리 부분은 별도의 서비스에서 처리해야 함
- #22
=> feat: 가맹점/창고/반품 폐기 등록 및 가맹점 관리자/창고 관리자/ 일반,책임 관리자 폐기 조회

src/main/java/com/harusari/chainware/auth/service/AuthServiceImpl.java, src/main/java/com/harusari/chainware/auth/service/CustomUserDetailsService.java, src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java, src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepository.java, src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryCustom.java, src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryImpl.java
Closes #43 
- 회원 인증 및 조회 로직에서 이메일 중복 확인 쿼리에서 `member.isDeleted.eq(false)` 조건 삭제
- 탈퇴하지 않은 회원을 조회하는`findActiveMemberByEmail()` 추가
- `SecurityPolicy`에서 누락된 `/api/v1/email-exists` 엔드포인트 추가
- #43
=> refactor: 회원 이메일 중복 확인 시 탈퇴 여부 조건 제거 및 회원 조회 쿼리에 탈퇴 여부 조건 추가

src/main/java/com/harusari/chainware/config/security/SecurityConfig.java, src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java, src/main/java/com/harusari/chainware/exception/member/InvalidCurrentPasswordException.java, src/main/java/com/harusari/chainware/exception/member/InvalidPasswordChangeException.java, src/main/java/com/harusari/chainware/exception/member/MemberErrorCode.java, src/main/java/com/harusari/chainware/exception/member/PasswordConfirmationMismatchException.java, src/main/java/com/harusari/chainware/exception/member/PasswordSameAsCurrentException.java, src/main/java/com/harusari/chainware/exception/member/handler/MemberExceptionHandler.java, src/main/java/com/harusari/chainware/member/command/application/controller/MemberCommandController.java, src/main/java/com/harusari/chainware/member/command/application/dto/request/PasswordChangeRequest.java, src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandService.java, src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandServiceImpl.java, src/main/java/com/harusari/chainware/member/command/domain/aggregate/Member.java, src/main/java/com/harusari/chainware/member/command/domain/repository/MemberCommandRepositoryCustom.java, src/main/java/com/harusari/chainware/member/command/infrastructure/repository/JpaMemberCommandRepository.java, src/main/java/com/harusari/chainware/member/command/infrastructure/repository/MemberCommandRepositoryCustomImpl.java
Closes #45 
- 비밀번호를 변경할 때 현재 비밀번호가 일치하는지 검증하는 기능 구현
- 변경할 비밀번호가 8자리 이상인지 검증하는 기능 구현
- 변경할 비밀번호와 변경할 비밀번호 확인 값이 서로 같은지 검증하는 기능 구현
- 현재 비밀번호와 변경할 비밀번호가 같으면 예외를 발생시키는 기능 구현
- 데이터베이스에 변경할 비밀번호로 업데이트하는 기능 구현
- `SecurityPolicy`에 비밀번호 엔드포인트 추가
- #45
=> feat: 비밀번호 변경 기능 구현

src/main/java/com/harusari/chainware/common/dto/PageResponse.java, src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java, src/main/java/com/harusari/chainware/member/query/controller/MemberQueryController.java, src/main/java/com/harusari/chainware/member/query/dto/request/MemberSearchRequest.java, src/main/java/com/harusari/chainware/member/query/dto/response/MemberSearchResponse.java, src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryCustom.java, src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryImpl.java, src/main/java/com/harusari/chainware/member/query/service/MemberQueryService.java, src/main/java/com/harusari/chainware/member/query/service/MemberQueryServiceImpl.java
Closes #47 
- 마스터 권한만 접근 가능한 회원 프로필 조회 API를 구현
- 페이징 기능을 적용하여 한 페이지당 10개의 회원 프로필을 조회할 수 있도록 구현
- 다음 검색 조건을 옵션으로 적용할 수 있도록 구현
- 이메일, 이름, 전화번호, 생년월일, 권한, 직책, 탈퇴여부
- 가입일시 (아래 검색 방식 지원)
- 특정 날짜 단일 선택 검색
- 날짜 범위 검색 (from ~ to)
- 정렬 조건은 항상 member_id를 기준으로 오름차순 정렬
- #47
=> feat: 회원 정보 조회 기능 구현

src/main/java/com/harusari/chainware/member/command/application/controller/MemberCommandController.java, src/main/java/com/harusari/chainware/member/command/application/dto/request/UpdateMemberRequest.java, src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandService.java, src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandServiceImpl.java, src/main/java/com/harusari/chainware/member/command/domain/aggregate/Member.java, src/main/java/com/harusari/chainware/member/command/domain/repository/MemberCommandRepository.java
Closes #54 
- 회원 정보 수정 API 구현
- `SecurityPolicy`에 회원 정보 수정 API를 마스터 권한에 등록
- `memberId`로 회원 정보를 조회하는 기능 구현
- 이름, 권한, 전화번호, 직책, 탈퇴 여부를 수정하는 기능을 구현
- #54
=> feat: 회원 정보 수정 기능 구현

src/main/java/com/harusari/chainware/config/security/AccessType.java, src/main/java/com/harusari/chainware/config/security/SecurityConfig.java, src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
Closes #66
- Spring Security에서 동일 경로와 HTTP Method에 대해 권한별로 requestMatchers를 반복 등록하면서, 첫 번째 권한만 정상적으로 적용되고 이후 권한은 무시되는 문제를 hasAnyAuthority로 권한을 묶어 해결
- ROLE_BASED 권한 설정 시 requestMatchers 중복 호출 제거
- hasAnyAuthority를 사용하여 권한 목록 일괄 등록
- 동일 경로에서 다중 권한 적용 시 발생하던 Access Denied 문제 해결
- #66
=> fix: 동일 경로에 대해 다중 권한 개별 등록 시 발생하는 Access Denied 문제 수정

src/main/java/com/harusari/chainware/franchise/command/application/service/FranchiseCommandServiceImpl.java, src/main/java/com/harusari/chainware/franchise/common/mapstruct/FranchiseMapStruct.java, src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandServiceImpl.java, src/main/java/com/harusari/chainware/member/common/mapstruct/MemberMapStruct.java, src/main/java/com/harusari/chainware/vendor/command/application/service/VendorCommandServiceImpl.java, src/main/java/com/harusari/chainware/vendor/common/mapstruct/VendorMapStruct.java, src/main/java/com/harusari/chainware/warehouse/command/application/controller/WarehouseInventorySnapshotTestController.java, src/main/java/com/harusari/chainware/warehouse/command/application/service/InventorySnapshotSchedulerImpl.java, src/main/java/com/harusari/chainware/warehouse/command/mapper/WarehouseInventorySnapshotQueryMapper.java, src/main/java/com/harusari/chainware/warehouse/common/mapstruct/WarehouseMapStruct.java, src/main/resources/mappers/warehouse/WarehouseInventorySnapshotQueryMapper.xml
Closes #72 
- `MemberMapStruct` 에서 `unmappedSourcePolicy`, `unmappedTargetPolicy` 옵션 삭제
- `VendorMapStruct` 에서 `unmappedSourcePolicy`, `unmappedTargetPolicy` 옵션 삭제
- `WarehouseMapStruct` 에서 `unmappedSourcePolicy`, `unmappedTargetPolicy` 옵션 삭제
- `FranchiseMapStruct`에서 `unmappedSourcePolicy`, `unmappedTargetPolicy` 옵션 삭제
- 디렉토리명을 `mapper`에서 `mapstruct` 으로 변경
- #72
=> refactor: MapStruct 불필요한 옵션 제거 및 디렉토리명을 mapper에서 mapstruct으로 변경

src/main/java/com/harusari/chainware/franchise/common/mapstruct/FranchiseMapStruct.java, src/main/java/com/harusari/chainware/member/common/mapstruct/MemberMapStruct.java, src/main/java/com/harusari/chainware/product/command/application/service/ProductCommandServiceImpl.java, src/main/java/com/harusari/chainware/product/common/mapstruct/ProductMapStruct.java, src/main/java/com/harusari/chainware/vendor/common/mapstruct/VendorMapStruct.java, src/main/java/com/harusari/chainware/warehouse/common/mapstruct/WarehouseMapStruct.java
Closes #79 
- `@Mapper`에 `unmappedSourcePolicy`, `unmappedTargetPolicy` 옵션 추가
- `ReportingPolicy.IGNORE` 설정으로 빌드 경고 무시하도록 변경
- `Product`에서 사용하는 `MapStruct`를 `ProductMapper`에서 `ProductMapStruct`으로 변경
- `ProductCommandServiceImpl`에서 잘못 `import`된 `ProductMapper` 수정
- #79
=> refactor: MapStruct 매핑 시 unmapped 경고 무시하도록 설정 변경

src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java, src/main/java/com/harusari/chainware/franchise/command/application/controller/FranchiseCommandController.java, src/main/java/com/harusari/chainware/franchise/query/controller/FranchiseQueryController.java, src/main/java/com/harusari/chainware/franchise/query/dto/request/FranchiseSearchRequest.java, src/main/java/com/harusari/chainware/franchise/query/dto/resposne/FranchiseSearchResponse.java, src/main/java/com/harusari/chainware/franchise/query/repository/FranchiseQueryRepository.java, src/main/java/com/harusari/chainware/franchise/query/repository/FranchiseQueryRepositoryCustom.java, src/main/java/com/harusari/chainware/franchise/query/repository/FranchiseQueryRepositoryImpl.java, src/main/java/com/harusari/chainware/franchise/query/service/FranchiseQueryService.java, src/main/java/com/harusari/chainware/franchise/query/service/FranchiseQueryServiceImpl.java
Closes #99 
- `FranchiseQueryService`에 가맹점 목록 조회 메서드 정의
- QueryDSL을 사용하여 가맹점 목록을 페이징 조회하는 쿼리 작성
- `contract_end_date` 기준 오름차순 정렬 적용
- `PageRequest`를 사용하여 요청 페이지 처리 (크기: 10)
- `FranchiseQueryController`에 조회 API(`/api/v1/franchises`) 구현
- 응답 DTO(`FranchiseListResponse`) 정의 및 매핑 처리
- 인증된 사용자의 권한(Role)에 따라 접근 제어 (General/Senior만 허용)
- 검색 조건(가맹점명, 주소, 가맹점 상태, 계약일)을 통해 목록을 조회하는 기능 구현
- #99
=> feat: 가맹점 목록 조회 기능 구현

src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java, src/main/java/com/harusari/chainware/franchise/query/controller/FranchiseQueryController.java, src/main/java/com/harusari/chainware/franchise/query/dto/resposne/FranchiseSearchDetailResponse.java, src/main/java/com/harusari/chainware/franchise/query/repository/FranchiseQueryRepositoryCustom.java, src/main/java/com/harusari/chainware/franchise/query/repository/FranchiseQueryRepositoryImpl.java, src/main/java/com/harusari/chainware/franchise/query/service/FranchiseQueryService.java, src/main/java/com/harusari/chainware/franchise/query/service/FranchiseQueryServiceImpl.java
Closes #101 
- 가맹점 상세 조회 API 구현
- `SecurityPolicy`에 엔드포인트, `HTTP Method`, 권한 추가
- `FranchiseSearchDetailResponse`에 필요한 필드 추가
- `QueryDSL`로 가맹점 상세 정보 조회하는 쿼리 작성
- #101
=> feat: 가맹점 상세 조회 기능 구현

src/main/java/com/harusari/chainware/category/command/application/controller/CategoryCommandController.java, src/main/java/com/harusari/chainware/category/command/application/controller/TopCategoryCommandController.java, src/main/java/com/harusari/chainware/category/query/controller/CategoryQueryController.java, src/main/java/com/harusari/chainware/contract/command/application/controller/ContractCommandController.java, src/main/java/com/harusari/chainware/contract/command/application/dto/request/ContractCreateRequest.java, src/main/java/com/harusari/chainware/contract/command/application/dto/request/ContractUpdateRequest.java, src/main/java/com/harusari/chainware/contract/query/controller/VendorProductContractQueryController.java, src/main/java/com/harusari/chainware/exception/contract/handler/ContractExceptionHandler.java, src/main/java/com/harusari/chainware/product/command/application/controller/ProductCommandController.java, src/main/java/com/harusari/chainware/product/command/application/dto/request/ProductCreateRequest.java, src/main/java/com/harusari/chainware/product/command/application/dto/request/ProductUpdateRequest.java, src/main/java/com/harusari/chainware/product/query/controller/ProductQueryController.java, src/test/java/com/harusari/chainware/category/command/application/controller/CategoryCommandControllerTest.java, src/test/java/com/harusari/chainware/category/command/application/controller/TopCategoryCommandControllerTest.java, src/test/java/com/harusari/chainware/category/command/application/service/CategoryCommandServiceImplTest.java, src/test/java/com/harusari/chainware/category/command/application/service/TopCategoryCommandServiceImplTest.java, src/test/java/com/harusari/chainware/contract/command/application/controller/ContractCommandControllerTest.java, src/test/java/com/harusari/chainware/contract/command/application/service/ContractServiceImplTest.java, src/test/java/com/harusari/chainware/contract/query/service/VendorProductContractServiceImplTest.java, src/test/java/com/harusari/chainware/product/command/application/controller/ProductCommandControllerTest.java, src/test/java/com/harusari/chainware/product/command/application/service/ProductCommandServiceImplTest.java, src/test/java/com/harusari/chainware/product/query/controller/ProductQueryControllerTest.java
Closes #107 
- 카테고리, 제품, 거래처별 제품 컨트롤러에 스웨거 적용
- #107
=> docs: 카테고리, 제품, 거래처별 제품 컨트롤러에 Swagger 문서화 어노테이션 추가

src/main/java/com/harusari/chainware/delivery/command/application/dto/request/DeliveryStartItem.java, src/main/java/com/harusari/chainware/delivery/command/application/dto/request/DeliveryStartRequest.java, src/main/java/com/harusari/chainware/delivery/command/application/service/DeliveryCommandServiceImpl.java, src/main/java/com/harusari/chainware/delivery/exception/DeliveryErrorCode.java, src/main/java/com/harusari/chainware/takeback/command/domain/repository/TakeBackDetailRepository.java, src/main/java/com/harusari/chainware/warehouse/command/domain/aggregate/WarehouseOutbound.java, src/main/java/com/harusari/chainware/warehouse/command/domain/repository/WarehouseOutboundRepository.java, src/test/java/com/harusari/chainware/delivery/command/application/controller/DeliveryCommandControllerTest.java, src/test/java/com/harusari/chainware/delivery/command/application/service/DeliveryCommandServiceImplTest.java
Closes #114 
- 운송장 번호 등록 위치를 사용자 수동 등록에서 시스템에서 제공으로 변경
- 배송 시작 시 주문/재배송 제품 상세 정보에 대한 창고 출고 등록
- 반품 반려의 재배송에 대한 배송의 시작 기능 구현
- #114
=> feat: 재배송 및 신규 배송에 대한 창고 출고 등록

src/main/java/com/harusari/chainware/member/command/application/dto/request/warehouse/WarehouseCreateRequest.java, src/main/java/com/harusari/chainware/vendor/command/application/service/VendorCommandService.java, src/main/java/com/harusari/chainware/vendor/command/application/service/VendorCommandServiceImpl.java, src/main/java/com/harusari/chainware/warehouse/command/application/dto/request/WarehouseUpdateRequest.java, src/main/java/com/harusari/chainware/warehouse/command/application/dto/response/WarehouseCommandResponse.java, src/main/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandServiceImpl.java, src/main/java/com/harusari/chainware/warehouse/command/domain/aggregate/Warehouse.java, src/main/java/com/harusari/chainware/warehouse/common/mapstruct/WarehouseMapStruct.java, src/test/java/com/harusari/chainware/warehouse/command/application/controller/WarehouseCommandControllerTest.java, src/test/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandServiceImplTest.java
Closes #127 
- Address VO 내장 타입(Embedded Type) 매핑으로 리팩토링
- 창고 정보 생성 시 주소 필드를 `AddressRequest`으로 수정
- `WarehouseMapStruct`에서 주소 값도 매핑할 수 있도록 코드 수정
- `WarehouseCommandServiceImpl`에서 주소 정보를 업데이트할 때 `AddRequest` 객체를 `Address` vo로 매핑하도록 코드 추가
- `VendorCommandService`에서 사용하지 않은 창고 생성 메서드 삭제
- 관련 테스트 코드 수정
- 창고 테이블에 우편번호, 도로명 주소, 상세 주소 컬럼 추가
- 노션에 DDL-v35 참고
- #127
=> refactor: 창고 주소를 우편번호, 도로명 주소, 상세 주소로 세분화

src/main/java/com/harusari/chainware/auth/model/CustomUserDetails.java, src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java, src/main/java/com/harusari/chainware/member/command/application/controller/MemberCommandController.java, src/main/java/com/harusari/chainware/member/command/application/dto/request/UpdateMyInfoRequest.java, src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandService.java, src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandServiceImpl.java, src/main/java/com/harusari/chainware/member/command/domain/aggregate/Member.java, src/main/java/com/harusari/chainware/member/query/controller/MemberQueryController.java, src/main/java/com/harusari/chainware/member/query/dto/response/MyMemberDetailResponse.java, src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryCustom.java, src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryImpl.java, src/main/java/com/harusari/chainware/member/query/service/MemberQueryService.java, src/main/java/com/harusari/chainware/member/query/service/MemberQueryServiceImpl.java
Closes #142 
- `SecurityPolicy`에서 엔드포인트를 `Permit All`, `Authenticated`, `Role Based` 순서로 변경
- 회원 본인 정보를 수정하는 API 구현
- `@AuthenticationPrincipal CustomUserDetails userDetails`를 컨트롤러에 추가하여, 로그인 사용자가 본인의 정보를 수정할 수 있도록 함
- 서비스 로직에서 회원 정보를 조회해서 JPA 변경 감지 기능으로 회원 정보를 변경하는 기능 구현
- 회원 본인 정보를 조회하는 API 구현
- `@AuthenticationPrincipal CustomUserDetails userDetails`를 컨트롤러에 추가하여, 로그인 사용자가 본인의 정보를 조회할 수 있도록 함
- 회원 정보는 `memberId`, 이메일, 이름, 권한명, 전화번호, 생년월일, 직책 정보를 제공하는 기능 구현
- #142
=> feat: 회원 개인의 정보 조회, 수정 기능 구현

src/main/java/com/harusari/chainware/franchise/command/application/dto/request/UpdateFranchiseRequest.java, src/main/java/com/harusari/chainware/franchise/command/application/service/FranchiseCommandServiceImpl.java, src/main/java/com/harusari/chainware/franchise/command/domain/aggregate/Franchise.java, src/test/java/com/harusari/chainware/franchise/command/application/service/FranchiseCommandServiceImplTest.java, src/test/java/com/harusari/chainware/franchise/command/domain/aggregate/FranchiseTest.java
Closes #154 
- `UpdateFranchiseRequest`에 계약 시작일, 종료일 필드 추가
- `Franchise` 엔티티에서 `updateFranchise()` 메서드에 인자값으로 계약 시작일, 종료일을 받도록 수정
- #154
=> refactor: 가맹점 수정 기능에 계약 시작일, 종료일을 변경하는 기능 구현

src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryImpl.java
Closes #190 
- 회원 목록 조회 total count 쿼리에서 누락된 `position`, `isDeleted` 조건 추가
- #190
=> fix: 회원 목록 조회 count 쿼리에 position, isDeleted 조건 추가 

src/main/java/com/harusari/chainware/common/controller/HealthCheckController.java, src/main/java/com/harusari/chainware/config/RedisConfig.java, src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
Closes #194 
- 시스템 헬스체크를 위한 `HealthCheckController`를 추가
- 인증 없이 접근할 수 있도록 `/api/v1/health/check`를 `SecurityPolicy`에 등록
- Redis SSL 설정 키가 잘못되어 있어 `${spring.data.redis.ssl:false}` → `${spring.data.redis.ssl.enabled:false}`로 수정
- #194
=> feat: 헬스체크 API 추가 및 Redis SSL 프로퍼티명 수정

src/main/java/com/harusari/chainware/auth/controller/AuthController.java, src/main/resources/application-prod.yml, src/main/resources/application.yml
Closes #200 
- 배포 환경과 개발 환경에 따라 리프레시 토큰의 쿠키 설정(Secure, SameSite)을 동적으로 처리하도록 쿠키를 환경별로 다르게 설정하는 기능을 추가
- `application.yml`, `application-prod.yml`에 환경별 쿠키 옵션 추가
- `@Value` 어노테이션으로 쿠키 설정값 주입
- `createRefreshTokenCookie` 및 `createDeleteRefreshTokenCookie`에서 쿠키 설정을 동적으로 처리하도록 수정
- #200
=> fix: 환경별 쿠키 옵션 동적 처리 기능 추가

src/main/java/com/harusari/chainware/config/security/SecurityConfig.java, src/main/resources/application-prod.yml, src/main/resources/application.yml
Closes #212 
- CORS 허용 Origin을 환경변수로 관리하여 개발과 운영 환경에 따라 유연하게 CORS 설정이 적용되도록 변경
- #212
=> refactor: CORS 허용 Origin을 환경변수 기반으로 개발·운영 환경 분리

src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java
Closes #231 
- `/api/v1/auth/password`에서 `/api/v1/members/password`으로 수정 
- `HttpMethod` `POST`에서 `PUT`으로 수정
- #231
=> fix: SecurityPolicy에 잘못 등록된 비밀번호 변경 엔드포인트 수정

src/main/java/com/harusari/chainware/takeback/query/repository/TakeBackQueryRepositoryImpl.java
Closes #245 
- `FranchiseInfo DTO`의 필드 선언 순서와 다르게 `QueryDSL`에서 값을 매핑하여 데이터가 잘못 들어가는 문제가 있어서 `DTO` 순서에 맞게 매핑 순서를 수정
- #245
=> fix: FranchiseInfo DTO 필드 순서에 맞게 QueryDSL 결과 매핑 순서 수정

src/main/java/com/harusari/chainware/takeback/query/repository/TakeBackQueryRepositoryImpl.java
Closes #247 
- FranchiseInfo DTO 필드 순서에 맞게 QueryDSL 결과 매핑 순서 수정
- #247
=> fix: FranchiseInfo DTO 필드 순서에 맞게 QueryDSL 결과 매핑 순서 수정 (#247)
