harusari-chainware/harusari-chainware-spring

src/main/java/com/harusari/chainware/common/config/SwaggerConfig.java, src/main/java/com/harusari/chainware/common/dto/ApiResponse.java, src/main/resources/application-prod.yml, src/main/resources/application.yml
- swagger 설정 추가
- API 응답 DTO 생성
-
=> feat: 프로젝트 공통 설정 추가

src/main/java/com/harusari/chainware/config/SwaggerConfig.java, src/main/java/com/harusari/chainware/member/command/application/controller/MemberCommandController.java, src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandService.java, src/main/java/com/harusari/chainware/member/command/application/service/MemberCommandServiceImpl.java, src/main/java/com/harusari/chainware/member/command/domain/aggregate/Member.java, src/main/java/com/harusari/chainware/member/command/domain/repository/MemberRepository.java, src/main/java/com/harusari/chainware/member/command/infrastructure/repository/JpaMemberRepository.java, src/main/java/com/harusari/chainware/member/query/controller/MemberQueryController.java, src/main/java/com/harusari/chainware/member/query/mapper/MemberMapper.java, src/main/java/com/harusari/chainware/member/query/service/MemberQueryService.java, src/main/java/com/harusari/chainware/member/query/service/MemberQueryServiceImpl.java
- `Command/Query` 책임 분리를 위한 패키지 구조 정의
- `MemberCommandController`, `Service`, `Repository` 등 클래스 및 인터페이스 생성
- `MemberQueryController`, `Service`, `Mapper` 등 클래스 및 인터페이스 생성
- 도메인 모델(`Member`) 및 리포지토리 인터페이스 분리
- 각 계층의 구현체 클래스(`.Impl`) 생성만 진행, 세부 로직은 미구현 상태
=> feat: CQRS 기반의 회원 도메인 클래스 및 인터페이스 구조 초기 생성

src/main/java/com/harusari/chainware/statistics/query/controller/MenuSalesQueryController.java, src/main/java/com/harusari/chainware/statistics/query/dto/MenuSalesResponse.java, src/main/java/com/harusari/chainware/statistics/query/mapper/MenuSalesMapper.java, src/main/java/com/harusari/chainware/statistics/query/service/MenuSalesQueryService.java, src/main/java/com/harusari/chainware/statistics/query/service/MenuSalesQueryServiceImpl.java, src/main/java/com/harusari/chainware/vendor/command/application/dto/VendorCreateRequestDto.java, src/main/java/com/harusari/chainware/vendor/command/application/dto/VendorUpdateRequestDto.java, src/main/java/com/harusari/chainware/vendor/command/application/service/VendorCommandServiceImpl.java, src/main/java/com/harusari/chainware/vendor/command/domain/aggregate/Vendor.java, src/main/java/com/harusari/chainware/vendor/query/dto/VendorDetailDto.java, src/main/java/com/harusari/chainware/vendor/query/dto/VendorListDto.java, src/main/resources/mappers/statistics/MenuSalesMapper.xml, src/main/resources/mappers/vendor/VendorQueryMapper.xml
=> fix: vendorContact 제거

src/main/java/com/harusari/chainware/config/security/SecurityConfig.java, src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java, src/main/java/com/harusari/chainware/warehouse/command/application/controller/WarehouseCommandController.java, src/main/java/com/harusari/chainware/warehouse/command/application/dto/request/WarehouseInventoryCreateRequest.java, src/main/java/com/harusari/chainware/warehouse/command/application/dto/request/WarehouseInventoryUpdateRequest.java, src/main/java/com/harusari/chainware/warehouse/command/application/dto/request/WarehouseUpdateRequest.java, src/main/java/com/harusari/chainware/warehouse/exception/WarehouseErrorCode.java, src/test/java/com/harusari/chainware/warehouse/command/application/controller/WarehouseCommandControllerTest.java, src/test/java/com/harusari/chainware/warehouse/command/application/service/WarehouseCommandServiceImplTest.java
Closes #56
- 창고 컨텍스트에 대한 예외 처리 정비
- 창고에 대한 테스트코드 작성
- 창고에 대한 Security 적용
- #56
=> feat: 창고 관리 기능 및 테스트코드 작성

src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java, src/main/java/com/harusari/chainware/delivery/query/controller/DeliveryQueryController.java, src/main/java/com/harusari/chainware/delivery/query/dto/request/DeliverySearchRequest.java, src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryDetailInfo.java, src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryDetailResponse.java, src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryOrderInfo.java, src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryProductInfo.java, src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliverySearchResponse.java, src/main/java/com/harusari/chainware/delivery/query/dto/response/FranchiseInfo.java, src/main/java/com/harusari/chainware/delivery/query/dto/response/WarehouseInfo.java, src/main/java/com/harusari/chainware/delivery/query/repository/DeliveryQueryRepository.java, src/main/java/com/harusari/chainware/delivery/query/repository/DeliveryQueryRepositoryCustom.java, src/main/java/com/harusari/chainware/delivery/query/repository/DeliveryQueryRepositoryImpl.java, src/main/java/com/harusari/chainware/delivery/query/service/DeliveryQueryService.java, src/main/java/com/harusari/chainware/delivery/query/service/DeliveryQueryServiceImpl.java
Closes #76
- 배송 목록 조회 기능 구현
- 배송 상세 조회 기능 구현
- 창고 별 가맹점 테이블에 대한 요구사항 누락으로 창고 관련 제외
- #76
=> feat: 배송 기본 조회 기능 구현

src/main/java/com/harusari/chainware/franchise/command/application/dto/request/UpdateFranchiseRequest.java, src/main/java/com/harusari/chainware/franchise/command/application/service/FranchiseCommandServiceImpl.java, src/main/java/com/harusari/chainware/franchise/command/domain/aggregate/Franchise.java, src/main/java/com/harusari/chainware/franchise/command/domain/aggregate/FranchiseStatus.java, src/main/java/com/harusari/chainware/franchise/command/domain/repository/FranchiseCommandRepositoryImpl.java
Closes #97 
- 가맹점 상태값을 활성화, 비활성화에서 영업중, 휴점, 준비중, 폐점 상태로 변경
- 가맹점 정보 수정 로직에 가맹점 상태값을 변경하는 로직 추가
- DDL에 가맹점 상태값을 영업중, 휴점, 준비중, 폐점 상태로 변경
- #97
=> feat: 가맹점 상태를 변경하는 기능 구현

src/test/java/com/harusari/chainware/franchise/command/application/controller/FranchiseCommandControllerTest.java, src/test/java/com/harusari/chainware/franchise/command/application/service/FranchiseCommandServiceImplTest.java, src/test/java/com/harusari/chainware/franchise/command/domain/aggregate/FranchiseTest.java, src/test/java/com/harusari/chainware/franchise/query/controller/FranchiseQueryControllerTest.java, src/test/java/com/harusari/chainware/franchise/query/service/FranchiseQueryServiceImplTest.java
Closes #115 
- 가맹점 등록 테스트 작성
- 가맹점 수정 테스트 작성
- 가맹점 수정 예외 테스트 작성
- 가맹점 조회(페이징) 테스트 작성
- 가맹점 상세 조회 테스트 작성
- Controller 단위 테스트 작성
- Entity 단위 테스트 작성
- #115
=> test: 가맹점 테스트 코드 작성

src/test/java/com/harusari/chainware/franchise/command/application/service/FranchiseCommandServiceImplTest.java
Closes #117 
- `FranchiseCommandServiceImplTest` 내 `doReturn(...).when(...).toFranchise(...)` 제거
- `@Spy` 기반 MapStruct 실제 매핑 검증되도록 구조 변경
- `franchiseRepository.save()` 스텁을 `thenAnswer(invocation -> invocation.getArgument(0))` 방식으로 개선
- #117
=> test: FranchiseCommandServiceImplTest에서 MapStruct 실제 매핑 테스트로 변경

src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java, src/main/java/com/harusari/chainware/vendor/query/controller/VendorQueryController.java, src/main/java/com/harusari/chainware/vendor/query/dto/VendorListDto.java, src/main/java/com/harusari/chainware/vendor/query/service/VendorQueryServiceImpl.java, src/main/resources/mappers/vendor/VendorQueryMapper.xml
Closes #139
- 거래처 관련 Security 추가
- 거래처 목록 조회 시 주소 반환 추가
- #139
=> feat: 거래처 조회 시 주소 반환 추가

src/main/java/com/harusari/chainware/franchise/command/application/controller/FranchiseCommandController.java, src/main/java/com/harusari/chainware/franchise/query/controller/FranchiseQueryController.java
Closes #152 
- `FranchiseCommandController`에 스웨거 어노테이션 적용
- `FranchiseQueryController`에 스웨거 어노테이션 적용
- #152
=> docs: 가맹점 controller에 스웨거 어노테이션 적용

build.gradle, src/main/java/com/harusari/chainware/auth/service/AuthServiceImpl.java, src/main/java/com/harusari/chainware/config/security/SecurityConfig.java, src/main/java/com/harusari/chainware/member/common/utils/UserAgentUtils.java
- SecurityConfig에 CORS 설정
- uap 라이브러리 추가
- 브라우저 정보를 간략하게 가져올 수 있도록 코드 수정
=> refactor: CORS 설정 및 브라우저 정보를 가져오는 로직 수정

src/main/java/com/harusari/chainware/exception/auth/AuthErrorCode.java, src/main/java/com/harusari/chainware/member/query/dto/request/MemberSearchRequest.java, src/main/java/com/harusari/chainware/member/query/repository/MemberQueryRepositoryImpl.java, src/main/resources/application-prod.yml, src/main/resources/application.yml
=> refactor: 회원 조회 쿼리에 탈퇴 여부 옵션 추가

src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java, src/main/java/com/harusari/chainware/vendor/query/controller/VendorQueryController.java, src/main/java/com/harusari/chainware/vendor/query/dto/response/VendorContractInfoResponse.java, src/main/java/com/harusari/chainware/vendor/query/dto/response/VendorPresignedUrlResponse.java, src/main/java/com/harusari/chainware/vendor/query/repository/VendorQueryRepositoryCustom.java, src/main/java/com/harusari/chainware/vendor/query/repository/VendorQueryRepositoryImpl.java, src/main/java/com/harusari/chainware/vendor/query/service/VendorQueryService.java, src/main/java/com/harusari/chainware/vendor/query/service/VendorQueryServiceImpl.java
Closes #177
- 거래처 계약 정보 조회 API 구현
- `SecurityPolicy`에 거래처 계약 정보 엔드포인트, HTTP 메서드, 권한 정보 추가
- `VendorQueryRepositoryImpl`에 거래처 계약 정보 조회 쿼리 작성
- #177
=> feat: 거래처 계약 정보 조회 기능 구현

src/main/java/com/harusari/chainware/vendor/command/domain/aggregate/Vendor.java
Closes #192 
- `Vendor` 엔티티에서 vendorStatus 값을 `IN_PROGRESS`로 설정
- #192
=> refactor: 거래처 상태 기본 값을 IN_PROGRESS로 설정

src/main/java/com/harusari/chainware/warehouse/command/domain/aggregate/WarehouseInbound.java
Closes #
- refactor : 들여쓰기 수정
- #
=> refactor : 들여쓰기 수정

src/main/java/com/harusari/chainware/purchase/query/controller/PurchaseOrderQueryController.java, src/main/java/com/harusari/chainware/purchase/query/dto/PurchaseOrderListResponse.java, src/main/java/com/harusari/chainware/purchase/query/mapper/PurchaseOrderQueryMapper.java, src/main/java/com/harusari/chainware/purchase/query/service/PurchaseOrderQueryService.java, src/main/java/com/harusari/chainware/purchase/query/service/PurchaseOrderQueryServiceImpl.java, src/main/java/com/harusari/chainware/requisition/query/controller/RequisitionQueryController.java, src/main/java/com/harusari/chainware/requisition/query/dto/response/RequisitionListResponse.java, src/main/java/com/harusari/chainware/requisition/query/mapper/RequisitionQueryMapper.java, src/main/java/com/harusari/chainware/requisition/query/service/RequisitionQueryService.java, src/main/java/com/harusari/chainware/requisition/query/service/RequisitionQueryServiceImpl.java, src/main/resources/mappers/purchase_order/PurchaseOrderQueryMapper.xml, src/main/resources/mappers/requisition/RequisitionQueryMapper.xml
Closes #214 
- 품의 / 발주 추가 기능 마무리
- #214
=> refactor : 품의 / 발주 추가 기능 마무리

src/main/java/com/harusari/chainware/statistics/query/service/predictionComparison/PredictionComparisonQueryServiceImpl.java, src/main/java/com/harusari/chainware/takeback/query/repository/TakeBackQueryRepositoryImpl.java, src/main/resources/mappers/statistics/PredictionComparisonQueryMapper.xml
Closes #225 
- 오류 로직 수정
- #225
=> fix: 오류 로직 수정

src/main/java/com/harusari/chainware/contract/query/controller/VendorProductContractQueryController.java, src/main/java/com/harusari/chainware/contract/query/dto/response/VendorProductContractDto.java, src/main/java/com/harusari/chainware/contract/query/dto/response/VendorProductContractListDto.java, src/main/resources/mappers/contract/ContractQueryMapper.xml
Closes #227 
- 품의 등록 시 거래처 별 계약 품목 페이징 처리 오류 수정
- #227
=> refactor : 품의 등록 시 거래처 별 계약 품목 페이징 처리 오류 수정

src/main/java/com/harusari/chainware/contract/query/dto/response/VendorProductContractDto.java
=> fix : 거래처 별 계약 품목 조회 오류 수정

src/main/java/com/harusari/chainware/config/security/SecurityPolicy.java, src/main/java/com/harusari/chainware/warehouse/query/controller/WarehouseQueryController.java, src/main/java/com/harusari/chainware/warehouse/query/dto/request/WarehouseInventorySearchRequest.java, src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseInventoryQueryRepositoryImpl.java
Closes #233 
- warehouseSearchRequestDto에 warehouseId 추가
- #233
=> fix: warehouseSearchRequestDto에 warehouseId 추가

src/main/java/com/harusari/chainware/warehouse/query/repository/WarehouseInventoryQueryRepositoryImpl.java
Closes #237 
- 재고 상세 조회 시 동일한 출고 기록이 나오는 오류 수정
- 
- #237
=> fix: 재고 상세 조회 시 동일한 출고 기록이 나오는 오류 수정

src/main/java/com/harusari/chainware/takeback/query/dto/request/TakeBackSearchRequest.java, src/main/java/com/harusari/chainware/takeback/query/repository/TakeBackQueryRepositoryImpl.java
Closes #243 
- 반품 목록 조회 로직 수정
- main에 머지 시 필수로 설정해야 하는 사항을 작성 (없다면 섹션 삭제)
- 예: .env 수정, npm install, DDL 변경 등
- #243
=> fix: 반품 목록 조회 로직 수정

src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryDetailInfo.java, src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryDetailResponse.java, src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryProductInfo.java, src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryTakeBackInfo.java, src/main/java/com/harusari/chainware/delivery/query/dto/response/DeliveryTakeBackProductInfo.java, src/main/java/com/harusari/chainware/delivery/query/repository/DeliveryQueryRepositoryImpl.java
Closes #205
- 배송 상세 조회 시 재배송에 대한 정보 추가
- #205
=> refactor: 배송 조회 및 관리에 대한 DTO 수정
